sudo: false
language: php
notifications:
  email:
    on_success: never
    on_failure: change
branches:
  only:
  - master
  - "/^v?[0-9\\.]+/"
cache:
- composer
- "$HOME/.composer/cache"
php:
- '5.6'
- '7.0'
env:
- WP_VERSION=latest WP_MULTISITE=0
- WP_VERSION=nightly WP_MULTISITE=0
services:
- mysql
before_script:
- export PATH="$HOME/.composer/vendor/bin:$PATH"
- bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
- composer install
script:
- composer test
before_deploy:
- echo 'Making deploy packages...'
- rm -rfv .git
- rm -rfv bin
- rm -rfv tests
- rm -rfv .gitignore
- rm -rfv .travis.yml
- rm -rfv vendor
- rm -rfv composer.lock
- rm -rfv phpunit.xml.dist
- zip -r pattern.zip ./
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: Tjovtb6MfTDfn5RZbveoXMPpaTykSsVLQ1+Ow2IE8enww/mmqzY+3CXNFKxXE+IerSYXQL/42LHaNDYvV/W+FUDcIrNIm1QNc88WIpdnzcQd6dA1Gjfqs/02iOkwt+7n9zdTh6lqE5heiSG+Cva+EKq0mAO2asrWzwAkcJqhxpm29OlHAGJqHEHa/9V0LuWeB0/JlkHyze7kCF6S+w9M+4HVDOV+/hxhIj8VrTzvQHqeOhk8CTgoX6k9qDQxftS/O3kWYUNTwkHTuOg7Z9bATdsSXlOKgn/He4kkx+9mvJm3HqI+PuAQgAV+GSQLRk/VlUg88gnySJSe2eGbGQip6KZ75Cv7I5PqrC0bhcsSWhCp/q8t75pzP8hUxZmOnQbxWdS5D7UhLNrMj08XMGWji2fu19UpG+ZCuInkIfedto9SxFwIM9F/+28PsN1OKAq+d24+wgAdcs088KkhZSRgNVlmLcC2kUb5rD2QuBFmGYTNehkZWCPTKQ23D/RAaaEDn0OcWVESNHPjsuKsWQS8TNBi5tSVBMEQzxEQbhGHer0p1dN2ldJwH7jma3L2tZB3HADsDWXusM4ydRiCwJvZoFaiKgBMRKIb4pd653CE485DKt/A/S7dT78168cBOBxnrhTOKpzw0WCqQNiBMFab2OR9QMav80FpUHqQchyY6rE=
  file: pattern.zip
  on:
    repo: hametuha/pattern
    tags: true
    php: '7.0'
